/* ============================================================
   SOLENIX SOLUTIONS — PRODUCT CATALOG DATA
   ------------------------------------------------------------
   To add a new product, copy a block, paste it at the end of
   PRODUCTS, and update the fields. Add the photo (ideally a
   4:3 studio-style shot) to images/products/. The grid, search,
   filters and footer links all update automatically.
   ============================================================ */

const CATEGORIES = [
  "Clamps",
  "Base Plates & Brackets",
  "Fasteners & Hardware",
  "Rails & Structures",
  "Electrical & Earthing",
];

const PRODUCTS = [
  { sku: "01", name: "Alu Mid Clamp", category: "Clamps", image: "images/products/01.jpg",
    desc: "Aluminium mid clamp that locks two adjacent panels onto the mounting rail with a single bolt. Light, corrosion-resistant and quick to torque down.",
    tags: ["aluminium", "aluminum", "module clamp", "panel"] },
  { sku: "02", name: "Alu End Clamp", category: "Clamps", image: "images/products/02.jpg",
    desc: "Aluminium end clamp that secures the outer edge of the first and last panel in every row for a clean, firmly fixed array edge.",
    tags: ["aluminium", "aluminum", "module clamp", "panel"] },
  { sku: "03", name: "GI Spring Nut", category: "Fasteners & Hardware", image: "images/products/03.jpg",
    desc: "Galvanized spring channel nut that drops into strut channel and springs into position — fast, tool-free placement before bolting.",
    tags: ["galvanized", "channel nut", "spring channel nut"] },
  { sku: "04", name: "GI B4 Base Plate", category: "Base Plates & Brackets", image: "images/products/04.jpg",
    desc: "Welded galvanized B4 base plate that anchors vertical structure legs to the roof or civil foundation, pre-punched for anchor fasteners.",
    tags: ["galvanized", "foundation", "b4"] },
  { sku: "05", name: "GI Strut Base Plate", category: "Base Plates & Brackets", image: "images/products/05.jpg",
    desc: "Galvanized base plate for strut channel uprights. Gives every leg of the structure a stable, square seat on the mounting surface.",
    tags: ["galvanized", "foundation", "mounting"] },
  { sku: "06", name: "GI C Lip Base Plate", category: "Base Plates & Brackets", image: "images/products/06.jpg",
    desc: "Rigid galvanized base plate sized for C-lip profiles, spreading the structure load evenly into the foundation.",
    tags: ["galvanized", "c lip", "foundation"] },
  { sku: "07", name: "Wedge Anchor Fastener", category: "Fasteners & Hardware", image: "images/products/07.jpg",
    desc: "Expansion wedge anchor for fixing base plates into concrete. Expands as it tightens for heavy-duty pull-out strength.",
    tags: ["anchor bolt", "concrete", "fastner"] },
  { sku: "08", name: "Copper Bonded Earthing Rod", category: "Electrical & Earthing", image: "images/products/08.jpg",
    desc: "Copper-bonded earthing rods with strips for low-resistance grounding of solar arrays — long service life even in aggressive soil.",
    tags: ["grounding", "earth rod", "copper"] },
  { sku: "09", name: "GI Mid Clamp Set", category: "Clamps", image: "images/products/09.jpg",
    desc: "Complete galvanized mid-clamp kit — clamp, spring nut and bolt in one pack, ready to install straight from the carton.",
    tags: ["galvanized", "module clamp", "kit"] },
  { sku: "10", name: "GI End Clamp Set", category: "Clamps", image: "images/products/10.jpg",
    desc: "Galvanized end-clamp kit with full hardware for fixing the row's outer panels — matched parts, no mixing and matching on site.",
    tags: ["galvanized", "module clamp", "kit"] },
  { sku: "11", name: "GI Degree Hanger", category: "Base Plates & Brackets", image: "images/products/11.jpg",
    desc: "Galvanized angle hanger that sets and holds the tilt of the mounting structure. Multiple holes allow on-site adjustment.",
    tags: ["galvanized", "angle", "tilt", "bracket"] },
  { sku: "12", name: "GI Strut Jointer", category: "Fasteners & Hardware", image: "images/products/12.jpg",
    desc: "Slotted galvanized connector that splices two strut channel lengths into one continuous, load-bearing run.",
    tags: ["galvanized", "connector", "splice"] },
  { sku: "13", name: "GI Solgrip Clamp", category: "Clamps", image: "images/products/13.jpg",
    desc: "High-grip galvanized clamp with a deep jaw for a firm, slip-free hold — a dependable workhorse across mounting jobs.",
    tags: ["galvanized", "solgrip", "grip"] },
  { sku: "14", name: "Anti-Theft Clamps", category: "Clamps", image: "images/products/14.jpg",
    desc: "Security clamps that resist tampering and deter removal of installed panels — added peace of mind for open and remote sites.",
    tags: ["security", "lock", "theft"] },
  { sku: "15", name: "Alu Monorail", category: "Rails & Structures", image: "images/products/15.jpg",
    desc: "Low-profile aluminium mounting rail — light to carry up a roof, strong in span, with a channel that takes standard clamp hardware.",
    tags: ["aluminium", "aluminum", "mounting rail", "mono rail"] },
  { sku: "16", name: "GI Nut Bolt & Washer", category: "Fasteners & Hardware", image: "images/products/16.jpg",
    desc: "Galvanized nut, bolt and washer sets in standard sizes — consistent plating and threads for smooth assembly.",
    tags: ["galvanized", "hardware", "bolt"] },
  { sku: "17", name: "Lightning Arrester", category: "Electrical & Earthing", image: "images/products/17.jpg",
    desc: "Rooftop lightning arrester kit that intercepts strikes and routes the surge safely to earth, protecting panels and inverters.",
    tags: ["surge", "safety", "LA", "copper"] },
  { sku: "18", name: "Rawl Anchor Fastener", category: "Fasteners & Hardware", image: "images/products/18.jpg",
    desc: "Heavy-duty rawl bolts for anchoring structures into concrete and masonry, supplied in the common sizes installers reach for.",
    tags: ["anchor bolt", "concrete", "fastner"] },
  { sku: "19", name: "MC4 Connectors", category: "Electrical & Earthing", image: "images/products/19.jpg",
    desc: "Weatherproof MC4 plug-and-socket pairs for solar DC cabling — positive click-lock connections that stay sealed outdoors.",
    tags: ["dc connector", "cable", "coupler"] },
  { sku: "20", name: "Rafters JSW/Apollo", category: "Rails & Structures", image: "images/products/20.jpg",
    desc: "Branded JSW and Apollo GI rafters for solar structures — trusted steel, supplied cut to your project's spans.",
    tags: ["jsw", "apollo", "purlin", "structure"] },
  { sku: "21", name: "HDG Mid Clamp", category: "Clamps", image: "images/products/21.jpg",
    desc: "Hot-dip galvanized mid clamp with a thick zinc coat for maximum rust protection on coastal and high-exposure sites.",
    tags: ["hot dip galvanized", "module clamp"] },
  { sku: "22", name: "ACDB & DCDB Boxes", category: "Electrical & Earthing", image: "images/products/22.jpg",
    desc: "Pre-wired AC and DC distribution boxes with protection devices — safe isolation and surge protection for the whole plant.",
    tags: ["distribution box", "combiner", "acdb", "dcdb", "spd", "mcb"] },
  { sku: "23", name: "AC & DC Wires", category: "Electrical & Earthing", image: "images/products/23.jpg",
    desc: "Solar-grade AC and DC cables in standard sizes and coil lengths, ready for clean, compliant wiring runs.",
    tags: ["cable", "wire", "sqmm"] },
];
